global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'my-python-script'

receivers:
  - name: 'my-python-script'
    webhook_configs:
      - send_resolved: true
        url: 'http://172.17.0.1:8000'
