events {
  worker_connections 1024;
}

http {

  upstream grafana {
    server grafana:3000;
  }

  upstream prometheus {
    server prometheus:9090;
  }

  server {
    listen 80;

    # Grafana — основной дашборд
    location /grafana/ {
      proxy_pass http://grafana;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Prometheus UI — для отладки
    location /prometheus/ {
      auth_basic "Prometheus";
      auth_basic_user_file /etc/nginx/.htpasswd;
      proxy_pass http://prometheus/;
      proxy_set_header Host $host;
    }

    # Главная страница → редирект в Grafana
    location / {
      return 301 /grafana/;
    }
  }
}
